version: '3.7'

services:
  api:
    build: .
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - '4000:4000'
    environment:
      WAIT_HOSTS: db:27017

  db:
    image: mongo:4.2
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-data:/data/db
    # Muting logs
    logging:
      driver: none
